FROM patavi/worker-amqp

RUN unzip patavi.worker-0.3-standalone.jar pirate/slow.R 

ENTRYPOINT ["/var/lib/patavi/bin/patavi-worker", "--method", "slow", "--rserve", "-n", "1", "--file", "pirate/slow.R"]
